### ISSUE TITLE
pax-provision for 1.4 uses pax-runner 0.16.0 which fails when attempting to use spring-dm profile [PAXCONSTRUCT-100]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#117]
**[Ken Rimple](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a07c02b6-5294-4ee1-a95d-d79b70b617d9)** created **[PAXCONSTRUCT-100](https://ops4j1.jira.com/browse/PAXCONSTRUCT-100)** 

In using the pax-provision command with the spring-dm profile, I get an error on download that broke pax-runner 0.16.0. If I use the following command to start the pax-provisioning using 0.17.0 of the runner it works fine:

pax-provision -p spring-dm -f equinox – -Drunner=0.17.0

I had used pax-update in the bin directory of the scripts to rev to 1.4.

Could you update the dependency for the next revision of the pax-provision process to use the 0.17.0 runner by default?

Thanks,

Ken Rimple

Stack trace below:<br /> -&gt; Using default executor<br /> -&gt; Downloading bundles...<br /> -&gt; org.springframework.context.support : 117045 bytes `@` [ 396kBps ]<br /> ___<br /> / /<br /> / / Oops, there has been a problem!<br /> / / <br /> /__/ <br /> ___<br /> /__/

-&gt; java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.springframework/spring-support](https://ops4j1.jira.com/wiki/display/mvn/org.springframework%2Fspring-support) is not a valid bundle<br /> java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.springframework/spring-support](https://ops4j1.jira.com/wiki/display/mvn/org.springframework%2Fspring-support) is not a valid bundle<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:472)<br /> at org.ops4j.pax.runner.Run.start(Run.java:196)<br /> at org.ops4j.pax.runner.Run.main(Run.java:646)<br /> at org.ops4j.pax.runner.Run.main(Run.java:619)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.ops4j.pax.construct.lifecycle.ProvisionMojo.invokePaxRunner(ProvisionMojo.java:802)<br /> at org.ops4j.pax.construct.lifecycle.ProvisionMojo.deployRunnerNG(ProvisionMojo.java:780)<br /> at org.ops4j.pax.construct.lifecycle.ProvisionMojo.deployBundles(ProvisionMojo.java:477)<br /> at org.ops4j.pax.construct.lifecycle.ProvisionMojo.execute(ProvisionMojo.java:270)<br /> at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)<br /> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)<br /> at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)<br /> at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)<br /> at org.codehaus.classworlds.Launcher.main(Launcher.java:375)<br /> Caused by: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.springframework/spring-support](https://ops4j1.jira.com/wiki/display/mvn/org.springframework%2Fspring-support) is not a valid bundle<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.validateBundleAndGetFilename(PlatformImpl.java:774)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:655)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadBundles(PlatformImpl.java:457)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadPlatformBundles(PlatformImpl.java:508)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:199)<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:468)<br /> ... 29 more

---

**Affects:** 1.4
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

This is "working as designed" because we're following the Maven approach, I've updated the docs to explain this:



If you don't have Pax-Runner in your local Maven repository this command will automatically attempt to download the latest release. It will then continue to use this locally installed version of Pax-Runner unless you add -U to force it to check online for a later release, or -Drunner=version to temporarily use a different version.



A number of maven components work the same way - if you don't have them in your local repository, Maven downloads the latest version and then continues to use that unless you explicitly add -U to force a recheck. This provides a level of consistency (no automatic updates potentially breaking a working build) while it also means I don't have to continually release new editions of Pax-Construct as Pax-Runner is updated (which is quite often).



If you want to enforce a specific version in your build you can add this to the pom.xml:



&lt;plugin&gt;<br /> &lt;groupId&gt;org.ops4j&lt;/groupId&gt;<br /> &lt;artifactId&gt;maven-pax-plugin&lt;/artifactId&gt;<br /> &lt;version&gt;1.4&lt;/version&gt;<br /> &lt;configuration&gt;<br /> &lt;runner&gt;0.17.0&lt;/runner&gt;<br /> &lt;/configuration&gt;<br /> &lt;/plugin&gt;



which gives you full control over which version of Pax-Runner is used when provisioning.
