### ISSUE TITLE
Maven build crashes in Eclipse [PAXCONSTRUCT-128]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#140]
**[Former user](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ba7eaae4-09a2-439f-84ec-5bee28339264)** created **[PAXCONSTRUCT-128](https://ops4j1.jira.com/browse/PAXCONSTRUCT-128)** 

Since i installed the latest build of the m2eclipse maven plugin and running a maven package/install from the context menu in eclipse i get the following stacktrace:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.project.MavenProject.addPlugin(Lorg/apache/maven/model/Plugin;)V<br /> at org.ops4j.pax.construct.lifecycle.BundleCompilerMojo.mergeCompilerConfiguration(BundleCompilerMojo.java:102)<br /> at org.ops4j.pax.construct.lifecycle.BundleCompilerMojo.execute(BundleCompilerMojo.java:70)<br /> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:103)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:477)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:314)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:199)<br /> at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:460)<br /> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:334)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:70)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

Running the same command on the command line, it doesn't crash. It seems maven changed an interface in the newest version.

---

**Fixed in:** 1.5
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Looks to me more like a m2e rather then pax runner so I do not know what can we do about.

**Comment by ops4j-issues** [comment]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** commented

well its probably org.ops4j.pax.construct.lifecycle.BundleCompilerMojo.mergeCompilerConfiguration(..) accessing org.apache.maven.project.MavenProject.addPlugin(Lorg/apache/maven/model/Plugin;)V



which could be pax constructs problem, no ?

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

`@Tony`. Right. Moved.

**Comment by ops4j-issues** [comment]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** commented

Maven Pax Plugin uses 2.0.7 maven api, M2E 3.0-SNAPSHOT but api should be compatible so, probabaly have to check a bit more.

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Pax-Construct attempts to alter the compilation behaviour to better match OSGi, and to do this it relies on various Maven APIs which I guess have changed.



As a workaround look in the "poms/pom.xml" file and change:



```java
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.ops4j</groupId>
          <artifactId>maven-pax-plugin</artifactId>
          <!--
           | enable improved OSGi compilation support for the bundle life-cycle.
           | to switch back to the standard bundle life-cycle, move this setting
           | down to the maven-bundle-plugin section
          -->
          <extensions>true</extensions>                        <!-- MOVE THIS -->
        </plugin>
        <plugin>
          <groupId>org.apache.felix</groupId>
          <artifactId>maven-bundle-plugin</artifactId>
          <version>1.4.3</version>
        </plugin>
      </plugins>
    </pluginManagement>
```



to be:



```java
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.ops4j</groupId>
          <artifactId>maven-pax-plugin</artifactId>
          <!--
           | enable improved OSGi compilation support for the bundle life-cycle.
           | to switch back to the standard bundle life-cycle, move this setting
           | down to the maven-bundle-plugin section
          -->
        </plugin>
        <plugin>
          <groupId>org.apache.felix</groupId>
          <artifactId>maven-bundle-plugin</artifactId>
          <version>1.4.3</version>
          <extensions>true</extensions>                        <!-- TO HERE -->
        </plugin>
      </plugins>
    </pluginManagement>
```



ie. move the &lt;extensions&gt; element from the maven-pax-plugin to the maven-bundle-plugin.<br /> This will disable the Pax-Construct compilation mojo and re-enable standard compilation.

**Comment by ops4j-issues** [comment]
**[Former user](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ba7eaae4-09a2-439f-84ec-5bee28339264)** commented

I changed the poms/pom.xml as you mentioned it. it gave me a similar Exception.



Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.project.MavenProject.getGoalConfiguration(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/codehaus/plexus/util/xml/Xpp3Dom;<br /> at org.apache.felix.bundleplugin.JarPluginConfiguration.getPluginConfiguration(JarPluginConfiguration.java:74)<br /> at org.apache.felix.bundleplugin.JarPluginConfiguration.getCorePluginConfiguration(JarPluginConfiguration.java:68)<br /> at org.apache.felix.bundleplugin.JarPluginConfiguration.getArchiveConfiguration(JarPluginConfiguration.java:52)<br /> at org.apache.felix.bundleplugin.BundlePlugin.mergeMavenManifest(BundlePlugin.java:453)<br /> at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle(BundlePlugin.java:397)<br /> at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:273)<br /> at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:227)<br /> at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:218)<br /> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:103)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:477)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:314)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:199)<br /> at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:460)<br /> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:334)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:70)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

This last exception (getGoalConfiguration) can be solved by upgrading to m2e 0.9.9_200911171109 or later, see [https://issues.apache.org/jira/browse/FELIX-1601](https://issues.apache.org/jira/browse/FELIX-1601) for more details.

**Comment by ops4j-issues** [comment]
**[Andreas Pieber](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:091ea76a-e92a-4e3c-a442-ca0a64e4487c)** commented

ok, maven3 creates the same error and is also fixable with the same workaround; the question is: is there any way to permanently fix this problem?

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Fixed in r17101
