### ISSUE TITLE
maven-pax-plugin throws NPE  [PAXCONSTRUCT-131]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#143]
**[Madhanraj Meignanam](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:4b5236d4-d465-4eef-a52f-377769a467e3)** created **[PAXCONSTRUCT-131](https://ops4j1.jira.com/browse/PAXCONSTRUCT-131)** 

We are using maven-pax-plugin to read some of the POM properties during maven build that uses our custom maven plugin. the maven-pax-plugin throws an NPE in certain instances:

java.lang.NullPointerException<br /> [exec](https://ops4j1.jira.com/wiki/display/paxconstruct/exec) at java.util.Hashtable.put(Hashtable.java:775)<br /> [exec](https://ops4j1.jira.com/wiki/display/paxconstruct/exec) at java.util.Properties.setProperty(Properties.java:563)<br /> [exec](https://ops4j1.jira.com/wiki/display/paxconstruct/exec) at org.ops4j.pax.construct.util.XppPom.getProperties(XppPom.java:671)

The following method in rg.ops4j.pax.construct.util.XppPom

public Properties getProperties()<br /> {<br /> Properties properties = new Properties();

Xpp3Dom map = m_pom.getChild( "properties" );<br /> if( null != map )<br /> {<br /> Xpp3Dom[] entries = map.getChildren();<br /> for( int i = 0; i &lt; entries.length; i++ )

 { properties.setProperty( entries[i].getName(), entries[i].getValue() ); } 

}

return properties;<br /> }

needs to be changed to have the NULL check:

....<br /> if (null != map) {<br /> Xpp3Dom[] entries = map.getChildren();<br /> for (int i = 0; i &lt; entries.length; i++)

 { if (entries[i].getName() != null &amp;&amp; entries[i].getValue() != null) properties.setProperty(entries[i].getName(), entries[i] .getValue()); } 

}<br /> ...

We have extended this class and overridden the getProperties method to workaround this issue. Also, we had to use reflection to access some of the members that are not visible.

Please let me know if any more information is needed.

Thanks,<br /> Madhan

---

**Affects:** 1.4
**Fixed in:** 1.7.0
Votes: 0, Watches: 1

**Comment by ops4j-issues** [comment]
**[Andreas Pieber](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:091ea76a-e92a-4e3c-a442-ca0a64e4487c)** commented

I've no idea if this is still a valid problem, but since 1.4 is already released I've moved it to 1.5
