### ISSUE TITLE
NoClassDefFoundError: org/codehaus/plexus/util/xml/XmlStreamWriter using maven 2.0.5 [PAXCONSTRUCT-45]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#22]
**[Ingo Meyer](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:4221b384-7ad1-49e1-81a1-0215eb10a144)** created **[PAXCONSTRUCT-45](https://ops4j1.jira.com/browse/PAXCONSTRUCT-45)** 

Hi all,

i have installed the new pax-construct-0.5.1 on my mac and now i have<br /> an error i cannot solve by myselve.<br /> Previously i used 0.1.6 which worked fine.

Here is the error, i also tried with a new repository:

pax-create-bundle -p org.example.pkg -n test.bundle

[INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Scanning for projects...<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------

---

[INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Building examples.test (OSGi project)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) task-segment: [org.ops4j:maven-pax-plugin:0.5.1:create-<br /> bundle] (aggregator-style)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------

---

[INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: classpath.resource.loader.class =&gt;<br /> 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: velocimacro.messages.on =&gt; 'false'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: resource.loader =&gt; 'classpath'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: resource.manager.logwhenfound =&gt; 'false'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) **************************************************************<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Starting Jakarta Velocity v1.4<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) RuntimeInstance initializing.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Default Properties File: org/apache/velocity/runtime/defaults/<br /> velocity.properties<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Default ResourceManager initializing. (class<br /> org.apache.velocity.runtime.resource.ResourceManagerImpl)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Resource Loader Instantiated:<br /> org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ClasspathResourceLoader : initialization starting.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ClasspathResourceLoader : initialization complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ResourceCache : initialized. (class<br /> org.apache.velocity.runtime.resource.ResourceCacheImpl)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Default ResourceManager initialization complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive:<br /> org.apache.velocity.runtime.directive.Literal<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive:<br /> org.apache.velocity.runtime.directive.Macro<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive:<br /> org.apache.velocity.runtime.directive.Parse<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive:<br /> org.apache.velocity.runtime.directive.Include<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive:<br /> org.apache.velocity.runtime.directive.Foreach<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Created: 20 parsers.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : initialization starting.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : adding VMs from VM library template :<br /> VM_global_library.vm<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxconstruct/ERROR) ResourceManager : unable to find resource<br /> 'VM_global_library.vm' in any resource loader.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : error using VM library template<br /> VM_global_library.vm :<br /> org.apache.velocity.exception.ResourceNotFoundException: Unable to<br /> find resource 'VM_global_library.vm'<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : VM library template macro registration complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : allowInline = true : VMs can be defined inline<br /> in templates<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : allowInlineToOverride = false : VMs defined<br /> inline may NOT replace previous VM definitions<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : allowInlineLocal = false : VMs defined inline<br /> will be global in scope if allowed.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : initialization complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocity successfully started.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [pax:create-bundle](https://ops4j1.jira.com/wiki/display/pax/create-bundle)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxconstruct/ERROR) FATAL ERROR<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) org/codehaus/plexus/util/xml/XmlStreamWriter<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Trace<br /> java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/<br /> XmlStreamWriter<br /> at org.ops4j.pax.construct.util.PomUtils.readPom<br /> (PomUtils.java:310)<br /> at org.ops4j.pax.construct.util.DirUtils.createModuleTree<br /> (DirUtils.java:154)<br /> at<br /> org.ops4j.pax.construct.archetype.AbstractPaxArchetypeMojo.createModuleT<br /> ree(AbstractPaxArchetypeMojo.java:295)<br /> at<br /> org.ops4j.pax.construct.archetype.AbstractPaxArchetypeMojo.execute<br /> (AbstractPaxArchetypeMojo.java:213)<br /> at org.apache.maven.plugin.DefaultPluginManager.executeMojo<br /> (DefaultPluginManager.java:420)<br /> at<br /> org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals<br /> (DefaultLifecycleExecutor.java:539)<br /> at<br /> org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoa<br /> l(DefaultLifecycleExecutor.java:493)<br /> at<br /> org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal<br /> (DefaultLifecycleExecutor.java:463)<br /> at<br /> org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandle<br /> Failures(DefaultLifecycleExecutor.java:311)<br /> at<br /> org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(<br /> DefaultLifecycleExecutor.java:224)<br /> at<br /> org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute<br /> (DefaultLifecycleExecutor.java:143)<br /> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:<br /> 330)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:123)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke<br /> (NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke<br /> (DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:585)<br /> at org.codehaus.classworlds.Launcher.launchEnhanced<br /> (Launcher.java:315)<br /> at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)<br /> at org.codehaus.classworlds.Launcher.mainWithExitCode<br /> (Launcher.java:430)<br /> at org.codehaus.classworlds.Launcher.main(Launcher.java:375)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Total time: 6 seconds<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Finished at: Sun Nov 11 18:07:09 CET 2007<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Final Memory: 9M/16M<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO)<br /> ------------------------------------------------------------------------

So any help is welcome.

Thanks in advance<br /> Ingo

---

**Affects:** 0.5.0
**Fixed in:** 0.6.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

resolved using an internal class to catch the linkage error under maven 2.0.5<br /> fix will definitely be in 0.6.0 and will also be in 0.5.2 (to be released this week)

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Cleaning up resolved issues.
