### ISSUE TITLE
Use Apache Felix osgi-core 1.0.1 instead of osgi_core R4 [PAXCONSTRUCT-88]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#37]
**[Hendy Irawan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0d210b36-5d07-43fe-97f6-31159abdaec5)** created **[PAXCONSTRUCT-88](https://ops4j1.jira.com/browse/PAXCONSTRUCT-88)** 

Pax-Construct should default to using Apache Felix's osgi-core 1.0.1 (also in Maven central), which is OSGi R4.1 API, rather than (as of Pax Construct 1.3) OSGi R4 artifacts in Maven central.

Forwarded conversation<br /> Subject: pax-runner and osgi_core<br /> ------------------------

From: Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 3:26 AM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

this is strange:

ceefour`@caliva`:~/project/ops4j/pax-script$ pax-run.sh --platform=equinox --profile=log scan-pom:[file:pom.xml](file:pom.xml)<br /> ______ ________ __ __<br /> / __ / / __ / / / / /<br /> / ___/ / __ / _\ \ _/<br /> / / / / / / / _\ \ <br /> /_*/ /**/ /**/ /*/ /_/

Pax Runner from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> --------------------------------------------

-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Provision from [scan-pom:file:pom.xml](https://ops4j1.jira.com/wiki/display/scan-pom/file%3Apom.xml)<br /> -&gt; Using property [bundle.symbolicName=org.ops4j.pax.script](https://ops4j1.jira.com/wiki/display/paxconstruct/bundle.symbolicName%3Dorg.ops4j.pax.script)<br /> -&gt; Using property [bundle.namespace=org.ops4j.pax.script](https://ops4j1.jira.com/wiki/display/paxconstruct/bundle.namespace%3Dorg.ops4j.pax.script)<br /> -&gt; Installing bundle [

 {location=mvn:org.ops4j.pax.script/pax-script/1.0-SNAPSHOT,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installing bundle [

 {location=mvn:org.osgi/osgi_R4_core/1.0,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installing bundle [

 {location=mvn:org.osgi/osgi_R4_compendium/1.0,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installing bundle [

 {location=mvn:org.ops4j.pax.swissbox/pax-swissbox-lifecycle/0.2.0,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installing bundle [

 {location=mvn:org.ops4j.base/ops4j-base-lang/0.5.0,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installing bundle [

 {location=mvn:org.ops4j.pax.swissbox/pax-swissbox-extender/0.2.0,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installing bundle [

 {location=mvn:commons-logging/commons-logging-api/1.1,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Downloading bundles...<br /> -&gt; mvn:org.osgi/osgi_R4_core/1.0 : 444838 bytes `@` [ 2457kBps ]<br /> ___<br /> / /<br /> / / Oops, there has been a problem!<br /> / / <br /> /__/ <br /> ___<br /> /__/

-&gt; java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.osgi/osgi_R4_core/1.0](https://ops4j1.jira.com/wiki/display/mvn/org.osgi%2Fosgi_R4_core%2F1.0) is not a valid bundle<br /> java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.osgi/osgi_R4_core/1.0](https://ops4j1.jira.com/wiki/display/mvn/org.osgi%2Fosgi_R4_core%2F1.0) is not a valid bundle<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:433)<br /> at org.ops4j.pax.runner.Run.start(Run.java:156)<br /> at org.ops4j.pax.runner.Run.main(Run.java:545)<br /> at org.ops4j.pax.runner.Run.main(Run.java:518)<br /> Caused by: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.osgi/osgi_R4_core/1.0](https://ops4j1.jira.com/wiki/display/mvn/org.osgi%2Fosgi_R4_core%2F1.0) is not a valid bundle<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.validateBundleAndGetFilename(PlatformImpl.java:684)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:565)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadBundles(PlatformImpl.java:399)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:197)<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:429)<br /> ... 3 more<br /> ceefour`@caliva`:~/project/ops4j/pax-script$ svn info<br /> Path: .<br /> URL: [https://scm.ops4j.org/repos/ops4j/laboratory/users/ceefour/pax-script](https://scm.ops4j.org/repos/ops4j/laboratory/users/ceefour/pax-script)<br /> Repository Root: [https://scm.ops4j.org/repos/ops4j](https://scm.ops4j.org/repos/ops4j)<br /> Repository UUID: 9b982a3c-3ae5-0310-a4bc-d9a3335569bd<br /> Revision: 12127<br /> Node Kind: directory<br /> Schedule: normal<br /> Last Changed Author: ceefour<br /> Last Changed Rev: 12127<br /> Last Changed Date: 2008-06-27 02:05:47 +0700 (Fri, 27 Jun 2008)

any suggestions? deleting/refreshing the m2 repo in respect to the suspecting file is not helping

pax-run.sh by itself runs just fine though...

– <br /> Best regards,<br /> Hendy Irawan ----------<br /> From: Stuart McCulloch &lt;stuart.mcculloch`@jayway`.net&gt;<br /> Date: Fri, Jun 27, 2008 at 3:48 AM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

2008/6/26 Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;:

this is strange:

no actually, it's correct - if you crack open that jarfile<br /> you will find it's not actually a bundle (no metadata)

the core artifact is only meant to be used for compiling<br /> against, not deploying, because all OSGi frameworks<br /> will provide the core classes by default - and including<br /> another bundle with same/different versions of these<br /> classes is not a good idea :smile:

note that the pax-plugin / pax-provision automatically<br /> exclude non-bundle dependencies for you by checking<br /> the manifest before passing them onto pax-runner

you can also mark dependencies as &lt;optional&gt; and<br /> pax-plugin / pax-provision won't try to deploy them

I don't think pax-runner does anything like this itself,<br /> if you want full maven support use pax-provision :smile:

_______________________________________________<br /> general mailing list<br /> general`@lists`.ops4j.org<br /> [http://lists.ops4j.org/mailman/listinfo/general](http://lists.ops4j.org/mailman/listinfo/general)

– <br /> Cheers, Stuart<br /> _______________________________________________<br /> general mailing list<br /> general`@lists`.ops4j.org<br /> [http://lists.ops4j.org/mailman/listinfo/general](http://lists.ops4j.org/mailman/listinfo/general)

----------<br /> From: Stuart McCulloch &lt;stuart.mcculloch`@jayway`.net&gt;<br /> Date: Fri, Jun 27, 2008 at 3:52 AM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

2008/6/26 Stuart McCulloch &lt;stuart.mcculloch`@jayway`.net&gt;:

FYI, the core dependency is being pulled in by this option:which spots the org.osgi/osgi_R4_core/1.0 dependency<br /> in your pom.xml - to stop this from happening you'll either<br /> need to put that dependency somewhere else (ie. some<br /> parent pom) or use the pax-provision script instead...

this is also why the default pax-run.sh command passes

– <br /> Cheers, Stuart<br /> _______________________________________________<br /> general mailing list<br /> general`@lists`.ops4j.org<br /> [http://lists.ops4j.org/mailman/listinfo/general](http://lists.ops4j.org/mailman/listinfo/general)

----------<br /> From: Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 12:04 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

Thanks, but:

&lt;dependency&gt;<br /> &lt;groupId&gt;org.osgi&lt;/groupId&gt;<br /> &lt;artifactId&gt;osgi_R4_core&lt;/artifactId&gt;<br /> &lt;version&gt;1.0&lt;/version&gt;<br /> &lt;scope&gt;provided&lt;/scope&gt;<br /> &lt;optional&gt;true&lt;/optional&gt;<br /> &lt;/dependency&gt;<br /> &lt;dependency&gt;<br /> &lt;groupId&gt;org.osgi&lt;/groupId&gt;<br /> &lt;artifactId&gt;osgi_R4_compendium&lt;/artifactId&gt;<br /> &lt;version&gt;1.0&lt;/version&gt;<br /> &lt;scope&gt;provided&lt;/scope&gt;<br /> &lt;optional&gt;true&lt;/optional&gt;<br /> &lt;/dependency&gt;

they're both marked as optional, why pax-run.sh still use them?

Doesn't it use the same scan-pom that's also used by pax-provision?<br /> Best regards,<br /> Hendy Irawan ----------<br /> From: Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 12:08 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

Thanks, using pax-provision solves the problem...

I won't use Pax Runner with Maven projects then...<br /> – <br /> Best regards,<br /> Hendy Irawan ----------<br /> From: Alin Dreghiciu &lt;adreghiciu`@gmail`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 12:58 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

It does use scan pom but is not the scan the project pom but a runtime<br /> generated pom.<br /> If you think that will be useful, that scan pom, does the same for<br /> optional dependencies (not take them in consideration, raise a jira<br /> issue.<br /> Alin Dreghiciu<br /> [http://www.ops4j.org](http://www.ops4j.org) - New Energy for OSS Communities - Open<br /> Participation Software.<br /> [http://www.qi4j.org](http://www.qi4j.org) - New Energy for Java - Domain Driven Development.<br /> [http://malaysia.jayway.net](http://malaysia.jayway.net) - New Energy for Projects - Great People<br /> working on Great Projects at Great Places<br /> ----------<br /> From: Stuart McCulloch &lt;stuart.mcculloch`@jayway`.net&gt;<br /> Date: Fri, Jun 27, 2008 at 12:59 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

2008/6/27 Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;:

the scan-pom handler is separate from the maven-pax-plugin and<br /> doesn't use any Maven code - so there are cases like this where<br /> it behaves differently (it doesn't merge poms with parents, etc.)

it should be straightforward to ignore optional dependencies in<br /> pax-runner-scanner-pom, just need to edit PomScanner.java to<br /> check for the optional element

– <br /> Cheers, Stuart<br /> _______________________________________________<br /> general mailing list<br /> general`@lists`.ops4j.org<br /> [http://lists.ops4j.org/mailman/listinfo/general](http://lists.ops4j.org/mailman/listinfo/general)

----------<br /> From: Alin Dreghiciu &lt;adreghiciu`@gmail`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 1:02 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

Stuart is right that osgi core should be provided by the osgi<br /> framework implementation but is also true that the dependencies from<br /> maven central pom are also not "good" as they are not the same as the<br /> one provided by OSGi Alliance. The problem with them is that are not<br /> bundles are simple plain jars.<br /> This is the reason why I uploaded th ecorrect artifacts from OSGi<br /> Alliance to ops4j repository. In plus I created them on OPS4J repo<br /> with the right version:

[http://repository.ops4j.org/maven2/org/osgi/org.osgi.core/](http://repository.ops4j.org/maven2/org/osgi/org.osgi.core/)<br /> [http://repository.ops4j.org/maven2/org/osgi/org.osgi.compendium/](http://repository.ops4j.org/maven2/org/osgi/org.osgi.compendium/)

On Thu, Jun 26, 2008 at 11:48 PM, Stuart McCulloch<br /> ----------<br /> From: Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 1:12 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;<br /> Cc: Peter Kriens &lt;peter.kriens`@aqute`.biz&gt;

1. So why is pax construct still using the maven central one?<br /> 2. Why nobody uploads the correct OSGi framework bundles to maven central? Ironically, there are quite many OSGi bundles in maven central but not OSGi itself?

I also had difficulty with pax-construct defaulting to OSGi R4, that I got stumped because I cannot use Bundle.getBundleContext(), so I then had to resort to apache felix's osgi-core 1.0.1.

I'm CC-ing this to Peter Kriens too because I think this is critical issue. To put it shortly, **OSGi R4.1 is not available from Maven central!**<br /> This is a major issue that needs to be fixed. I'd assume that Mr. Kriens is a pro-Maven too.

(A few weeks ago we were discussing why Equinox proper aren't available from Maven central... now OSGi itself)<br /> – <br /> Best regards,<br /> Hendy Irawan ----------<br /> From: Niclas Hedhman &lt;niclas`@hedhman`.org&gt;<br /> Date: Fri, Jun 27, 2008 at 1:19 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

He is also monitoring this list as much as time allows ;o)

Cheers<br /> Niclas<br /> ----------<br /> From: Stuart McCulloch &lt;stuart.mcculloch`@jayway`.net&gt;<br /> Date: Fri, Jun 27, 2008 at 1:27 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;<br /> Cc: Peter Kriens &lt;peter.kriens`@aqute`.biz&gt;

2008/6/27 Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;:

because 99% of the time that's all you need, and these days I have hardly any spare<br /> time at all, so I typically only fix the things that people bug me about / raise on JIRA

it would also add a implicit dependency to the OPS4J repo, which I'd prefer to avoid<br /> as the pax-construct archetypes are now available from the Maven central repository<br /> (the golden rule there is not to depend on external repos)

yep, that's why Alin added the latest artifacts to the OPS4J repository - uploads<br /> to the Maven central repo are typically only allowed by "owners" of the project

note that it's just a matter of changing the dependency in the pom.xml and adding<br /> the OPS4J repository - a bit annoying certainly, but not a complete blocker imho.

– <br /> Cheers, Stuart<br /> _______________________________________________<br /> general mailing list<br /> general`@lists`.ops4j.org<br /> [http://lists.ops4j.org/mailman/listinfo/general](http://lists.ops4j.org/mailman/listinfo/general)

----------<br /> From: Hendy Irawan &lt;hendy`@rainbowpurple`.com&gt;<br /> Date: Fri, Jun 27, 2008 at 2:47 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;<br /> Cc: Peter Kriens &lt;peter.kriens`@aqute`.biz&gt;

I agree. One of these 1% is when coding extenders...

Is it preferable to use org.apache.felix osgi-core/compendium v1.0.1 instead? (in the mean time) It's in Maven central, and complies with R4.1...

I agree with what Peter Kriens said, it doesn't give much benefit staying with older version. Developing in R4.1 doesn't mean that the bundle can't run with R4, its up to the bundle developer to use whichever feature it wants...

I agree with your comment below, it's a minor annoyance to use R4 framework as default. In my case the difference between R4.1 and R4 was so subtle yet important...

Agree. I'm running just fine now, yet still hoping that future Pax Construct projects will default to OSGi R4.1...

– <br /> Best regards,<br /> Hendy Irawan ----------<br /> From: Stuart McCulloch &lt;stuart.mcculloch`@jayway`.net&gt;<br /> Date: Fri, Jun 27, 2008 at 3:00 PM<br /> To: General OPS4J &lt;general`@lists`.ops4j.org&gt;

yes, that's certainly an option

true - when I first wrote those archetypes the Felix project didn't<br /> fully support R4.1, because it had only recently been released,<br /> but afaik the major frameworks now support the new method(s)

so I think we can now safely move over to use the Apache jars

they will, but I can't give a timeline at the moment<br /> (but more likely to be weeks rather than months)

– <br /> Cheers, Stuart<br /> _______________________________________________<br /> general mailing list<br /> general`@lists`.ops4j.org<br /> [http://lists.ops4j.org/mailman/listinfo/general](http://lists.ops4j.org/mailman/listinfo/general)

---

**Affects:** 1.3
Votes: 0, Watches: 1

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

The Apache Felix team is not planning on (re-)distributing the OSGi core API artifact in the future - instead the official OSGi jars will be deployed to central. The archetypes will be updated to the new versions once they have been deployed to central (currently we use the official R4 API jars)
