### ISSUE TITLE
IllegalStateException : No match found during execution of the following command : pax-create-bundle -n "reportincident bundle" -p org.ap ache.camel.example.reportincident.service -- "-Dspring" [PAXCONSTRUCT-102]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#43]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** created **[PAXCONSTRUCT-102](https://ops4j1.jira.com/browse/PAXCONSTRUCT-102)** 

D:\Dvlpt\Java\workspace-ganymede\osgi\reportincident.service.osgi&gt;pax-create-bundle -n "reportincident bundle" -p org.ap<br /> ache.camel.example.reportincident.service – "-Dspring"

D:\Dvlpt\Java\workspace-ganymede\osgi\reportincident.service.osgi&gt;mvn ~~N org.ops4j:maven-pax-plugin:1.5-SNAPSHOT:create~~<br /> bundle -Dpackage=org.apache.camel.example.reportincident.service -DbundleName="reportincident bundle" -DbundleGroupId= -<br /> Dversion=1.0-SNAPSHOT "-Dspring"<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Scanning for projects...<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Building org.apache.camel.example.reportincident.service.osgi (OSGi project)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) task-segment: [org.ops4j:maven-pax-plugin:1.5-SNAPSHOT:create-bundle](https://ops4j1.jira.com/wiki/display/org.ops4j/maven-pax-plugin%3A1.5-SNAPSHOT%3Acreate-bundle) (aggregator-style)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: classpath.resource.loader.class =&gt; 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoad<br /> er'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: velocimacro.messages.on =&gt; 'false'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: resource.loader =&gt; 'classpath'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Setting property: resource.manager.logwhenfound =&gt; 'false'.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) **************************************************************<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Starting Jakarta Velocity v1.4<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) RuntimeInstance initializing.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Resource Loader Instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ClasspathResourceLoader : initialization starting.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ClasspathResourceLoader : initialization complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ResourceCache : initialized. (class org.apache.velocity.runtime.resource.ResourceCacheImpl)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Default ResourceManager initialization complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive: org.apache.velocity.runtime.directive.Literal<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive: org.apache.velocity.runtime.directive.Macro<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive: org.apache.velocity.runtime.directive.Parse<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive: org.apache.velocity.runtime.directive.Include<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Loaded System Directive: org.apache.velocity.runtime.directive.Foreach<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Created: 20 parsers.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : initialization starting.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : adding VMs from VM library template : VM_global_library.vm<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxconstruct/ERROR) ResourceManager : unable to find resource 'VM_global_library.vm' in any resource loader.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : error using VM library template VM_global_library.vm : org.apache.velocity.exception.ResourceNotFo<br /> undException: Unable to find resource 'VM_global_library.vm'<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : VM library template macro registration complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : allowInline = true : VMs can be defined inline in templates<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocimacro : initialization complete.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Velocity successfully started.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [pax:create-bundle](https://ops4j1.jira.com/wiki/display/pax/create-bundle)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Selecting latest archetype release within version range [0,2)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) artifact org.ops4j.pax.construct:maven-archetype-osgi-bundle: checking for updates from central<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxconstruct/ERROR) FATAL ERROR<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) No match found<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Trace<br /> java.lang.IllegalStateException: No match found<br /> at java.util.regex.Matcher.group(Matcher.java:468)<br /> at org.ops4j.pax.construct.util.XppPathQuery.queryChildren(XppPathQuery.java:128)<br /> at org.ops4j.pax.construct.util.XppPom.findChildren(XppPom.java:979)<br /> at org.ops4j.pax.construct.util.XppPom.addModule(XppPom.java:441)<br /> at org.ops4j.pax.construct.archetype.AbstractPaxArchetypeMojo.prepareTarget(AbstractPaxArchetypeMojo.java:582)<br /> at org.ops4j.pax.construct.archetype.AbstractPaxArchetypeMojo.execute(AbstractPaxArchetypeMojo.java:336)<br /> at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav<br /> a:330)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)<br /> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)<br /> at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)<br /> at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)<br /> at org.codehaus.classworlds.Launcher.main(Launcher.java:375)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Total time: 9 seconds<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Finished at: Tue Feb 10 16:48:22 CET 2009<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Final Memory: 11M/19M<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------

---

**Fixed in:** 1.5
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

I haven't been able to reproduce this exception with either 1.4 or 1.5-SNAPSHOT



Could you provide a standalone testcase that recreates the problem (ie. one that I can use without missing dependencies, etc.) as well as any OS, Java, and Maven details. Fixing the exception is straightforward but it would be useful to find out how it got to be in that state - in case there are other things going on that also need fixing.



BTW, I won't have time to look into this in great detail until next week at the earliest.

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

The issue comes from the fact that the name of the bundle contains a space : -n "reportincident bundle"

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Interesting - I ran exactly that command line (with the space) on Windows + Maven 2.0.9 + JDK 6 and didn't get any exception... are you using a similar setup and are you running this command in a clean directory, or inside an existing pax-construct project?

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

I use a similar setup :



D:\Dvlpt\Java\workspace-ganymede\osgi\reportincident.service.osgi&gt;mvn -version<br /> Maven version: 2.0.9<br /> Java version: 1.6.0_07<br /> OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"



I run this command inside a pax project

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Try to recreate this and fix for 1.5

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

Problem does not exist anymore with pax-construct 1.4
