### ISSUE TITLE
java.lang.LinkageError when running 'mvn install' before 'mvn pax:eclipse' [PAXCONSTRUCT-110]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#45]
**[Joachim Kainz](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a8f1c63c-6c78-451a-a478-cac0e16b25e8)** created **[PAXCONSTRUCT-110](https://ops4j1.jira.com/browse/PAXCONSTRUCT-110)** 

I can reliably reproduce the issue described in [http://lists.ops4j.org/pipermail/general/2009q1/000787.html](http://lists.ops4j.org/pipermail/general/2009q1/000787.html). I am using the following simple script:

-------------~~bug.sh~~------------------<br /> #!/bin/sh<br /> rm -rf ~/.m2/repository<br /> pax-create-project -g com.jolira.pax -a bug -v 0.0.1-SNAPSHOT<br /> cd bug<br /> pax-wrap-jar -g org.apache.wicket -a wicket -v 1.4-rc2 – -DwrapTransitive<br /> exec mvn install pax:eclipse<br /> -------------~~bug.sh~~------------------

The error generated reads:

-------------~~mvn output~~------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxconstruct/ERROR) FATAL ERROR<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) loader constraint violation: when resolving method "org.codehaus.plexus.util.xml.Xpp3DomWriter.write(Lorg/codehaus/plexus/util/xml/XMLWriter;Lorg/codehaus/plexus/util/xml/Xpp3Dom;)V" the class loader (instance of org/codehaus/classworlds/RealmClassLoader) of the current class, org/ops4j/pax/construct/lifecycle/EclipseOSGiMojo, and the class loader (instance of org/codehaus/classworlds/RealmClassLoader) for resolved class, org/codehaus/plexus/util/xml/Xpp3DomWriter, have different Class objects for the type org/codehaus/plexus/util/xml/XMLWriter used in the signature<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Trace<br /> java.lang.LinkageError: loader constraint violation: when resolving method "org.codehaus.plexus.util.xml.Xpp3DomWriter.write(Lorg/codehaus/plexus/util/xml/XMLWriter;Lorg/codehaus/plexus/util/xml/Xpp3Dom;)V" the class loader (instance of org/codehaus/classworlds/RealmClassLoader) of the current class, org/ops4j/pax/construct/lifecycle/EclipseOSGiMojo, and the class loader (instance of org/codehaus/classworlds/RealmClassLoader) for resolved class, org/codehaus/plexus/util/xml/Xpp3DomWriter, have different Class objects for the type org/codehaus/plexus/util/xml/XMLWriter used in the signature<br /> at org.ops4j.pax.construct.lifecycle.EclipseOSGiMojo.addEmbeddedEntriesToEclipseClassPath(EclipseOSGiMojo.java:641)<br /> at org.ops4j.pax.construct.lifecycle.EclipseOSGiMojo.refactorForEclipse(EclipseOSGiMojo.java:463)<br /> at org.ops4j.pax.construct.lifecycle.EclipseOSGiMojo.writeBundleConfiguration(EclipseOSGiMojo.java:244)<br /> at org.ops4j.pax.construct.lifecycle.EclipseOSGiMojo.writeConfiguration(EclipseOSGiMojo.java:195)<br /> at org.apache.maven.plugin.ide.AbstractIdeSupportMojo.execute(AbstractIdeSupportMojo.java:494)<br /> at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)<br /> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br /> at java.lang.reflect.Method.invoke(Method.java:616)<br /> at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)<br /> at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)<br /> at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)<br /> at org.codehaus.classworlds.Launcher.main(Launcher.java:375)<br /> -------------~~mvn output~~------------

If I run 'exec mvn pax:eclipse' instead of 'exec mvn install pax:eclipse' as the last command in the script, the error does not happen.

I can work around this issue by removing my local repository before running 'mvn pax:eclipse', but this workaround is hardly scalable.

---

**Affects:** 1.4
**Attachments:**
* [bug.log](https://ops4j1.jira.com/secure/attachment/10263/bug.log)
* [bug.sh](https://ops4j1.jira.com/secure/attachment/10264/bug.sh)

Votes: 0, Watches: 1

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

This looks similar to the following thread:



[http://www.mail-archive.com/general@lists.ops4j.org/msg05945.html](http://www.mail-archive.com/general@lists.ops4j.org/msg05945.html)



the problem disappeared once Mike fixed his JDK installation



Which JDK are you using, could you post the results of running "which java" and "echo $JAVA_HOME" ?

**Comment by ops4j-issues** [comment]
**[Joachim Kainz](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a8f1c63c-6c78-451a-a478-cac0e16b25e8)** commented

Sorry for not getting back regarding this issue. I am using the JDK 1.6 that comes with Ubuntu 9.04.



I figured out that the problem only exists if I use Maven 2.0.9 from the Ubuntu repository. The dependencies of this package include libwagon and others, which I believe create the problem described above.



Instead of maven 2.0.9 from the repo I now use maven 2.1.0. Everything works like a charm.



I think this conclusively proves that this is not a pax-construct issue, but rather an issue with the particular maven install.

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Closing as requested
