### ISSUE TITLE
NPE on maven-inherit-plugin [PAXCONSTRUCT-77]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.construct#99]
**[Marvin Froeder](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2f7d8e97-b100-4e7d-9548-46a1bc359fa2)** created **[PAXCONSTRUCT-77](https://ops4j1.jira.com/browse/PAXCONSTRUCT-77)** 

I got this issue when I tried to extends maven-source plugin:<br /> D:\flex\workspace\rvin-mojo\source-mojo&gt;mvn clean install -e<br /> + Error stacktraces are turned on.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Scanning for projects...<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Building Source Maven Mojo<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) task-segment: [clean, install](https://ops4j1.jira.com/wiki/display/paxconstruct/clean%2C+install)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [clean:clean](https://ops4j1.jira.com/wiki/display/clean/clean)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Deleting directory D:\flex\workspace\rvin-mojo\source-mojo\target<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [plugin:descriptor](https://ops4j1.jira.com/wiki/display/plugin/descriptor)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Using 2 extractors.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Applying extractor for language: java<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Extractor for language: java found 1 mojo descriptors.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Applying extractor for language: bsh<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Extractor for language: bsh found 0 mojo descriptors.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [resources:resources](https://ops4j1.jira.com/wiki/display/resources/resources)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Using default encoding to copy filtered resources.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [compiler:compile](https://ops4j1.jira.com/wiki/display/compiler/compile)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Compiling 1 source file to D:\flex\workspace\rvin-mojo\source-mojo\target\classes<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) [inherit:inherit

 {execution: default} 

]<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Expanding: C:\repository\org\apache\maven\plugins\maven-source-plugin\2.0.4\maven-source-plugin-2.0.4.jar into D:\flex\workspace\rvin-mojo\source-mojo<br /> \target\plugins\maven-source-plugin<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Extending source plugin<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) package =&gt; jar<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxconstruct/ERROR) FATAL ERROR<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) null<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Trace<br /> java.lang.NullPointerException<br /> at org.codehaus.plexus.util.xml.Xpp3Dom.&lt;init&gt;(Xpp3Dom.java:73)<br /> at org.ops4j.pax.construct.inherit.PluginXml.mergeMojo(PluginXml.java:107)<br /> at org.ops4j.pax.construct.inherit.InheritMojo.mergePluginMojo(InheritMojo.java:279)<br /> at org.ops4j.pax.construct.inherit.InheritMojo.execute(InheritMojo.java:145)<br /> at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)<br /> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)<br /> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:585)<br /> at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)<br /> at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)<br /> at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)<br /> at org.codehaus.classworlds.Launcher.main(Launcher.java:375)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Total time: 9 seconds<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Finished at: Thu Apr 10 13:24:52 BRT 2008<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) Final Memory: 10M/20M<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) ------------------------------------------------------------------------

Can I provide any more details?

VELO

---

**Affects:** 1.0
**Fixed in:** maven-inherit-plugin 1.1
Votes: 0, Watches: 1

**Comment by ops4j-issues** [comment]
**[Marvin Froeder](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2f7d8e97-b100-4e7d-9548-46a1bc359fa2)** commented

I believe so.



[http://www.ops4j.org/projects/pax/construct/maven-inherit-plugin/apidocs/org/ops4j/pax/construct/inherit/InheritMojo.html](http://www.ops4j.org/projects/pax/construct/maven-inherit-plugin/apidocs/org/ops4j/pax/construct/inherit/InheritMojo.html)



VELO

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Moved to appropriate project (Pax-Construct)



Hi Marvin, I think I know what's happening - it looks like there's a misconfiguration, which is showing up as a NPE rather than an error message.<br /> Could you provide the top of the source code for your modified mojo, specifically the part with the `@extendsPlugin`, etc. tags so I can confirm this?



Thanks, Stuart

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Specifically, this line:



[INFO](https://ops4j1.jira.com/wiki/display/paxconstruct/INFO) package =&gt; jar



tells me that you've set the super-goal to be 'package' and the current goal to be 'jar'... ie. your mojo provides the goal 'jar' and you want to inherit from the 'package' goal in the maven-source-plugin. However, looking at the maven-source-plugin webpage, I can't see a 'package' goal, only 'source:jar'. This makes wonder whether you actually wanted the opposite... ie. your mojo is providing the 'package' goal which extends the 'jar' goal in the maven-source-plugin. If so then you should try the following:



`@extendsPlugin` source<br /> `@extendsGoal` jar<br /> `@goal` package



Hopefully this works for you - if not then let me know and I'll dig further ( either way I'll fix the NPE and make it report a proper error message instead :smile:

**Comment by ops4j-issues** [comment]
**[Marvin Froeder](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2f7d8e97-b100-4e7d-9548-46a1bc359fa2)** commented

This lines?



/**



* `@extendsPlugin` maven-source-plugin
* `@extendsGoal` package
* 
* `@goal` jar
* `@phase` package<br /> */



VELO

**Comment by ops4j-issues** [comment]
**[Marvin Froeder](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2f7d8e97-b100-4e7d-9548-46a1bc359fa2)** commented

Changing to <br /> `@extendsPlugin` source<br /> `@extendsGoal` jar



Works.



Thanks a lot =D



VELO

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Cool - I'll keep this issue open to turn that NPE into a more descriptive message - thanks

**Comment by ops4j-issues** [comment]
**[Marvin Froeder](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2f7d8e97-b100-4e7d-9548-46a1bc359fa2)** commented

Just a suggestion, show avaliable plugins/goals on error message.



And please, let me knwo when 1.1 is released.



VELO

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Fixed in trunk, will release maven-inherit-plugin 1.1 later today.

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

version 1.1 of the maven-inherit-plugin has been released.
